version: "1.0"

services:

  database:
    image: postgres:13
    container_name: matrix
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./docker/create_databases.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  proposal-operations:
    build:
      context: ./proposal.operations
    ports:
      - "91:91"
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      SPRING_SERVER_PORT: 91
      DB_URL: jdbc:postgresql://database:5432/web_proposals_api
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DRIVER_CLASS_NAME: org.postgresql.Driver
      DB_OPEN_VIEW: false
      DB_DDL_AUTO: update
      FLYWAY_ENABLED: true
      DB_SCHEMA: public
      BASE_LINE_ON_MIGRATE: true
      SWAGGER_DOC_ENABLED: true
      SWAGGER_UI_ENABLED: true
      SWAGGER_CONFIG_URL: /v3/api-docs/swagger-config
      SWAGGER_URL: /v3/api-docs