server:
  port: ${SPRING_SERVER_PORT:8081}

spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/web_proposals_api_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      mode: ${DB_SQL_MODE:always}
    platform: ${DB_PLATFORM:postgres}