server:
  port: ${SPRING_SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    hikari:
      schema: ${DB_SCHEMA}
  jpa:
    open-in-view: ${DB_OPEN_VIEW}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}

  flyway:
    enabled: ${FLYWAY_ENABLED}
    schemas: ${DB_SCHEMA}
    baselineOnMigrate: ${BASE_LINE_ON_MIGRATE}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration