server:
  port: ${SPRING_SERVER_PORT:8091}

spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/web_proposals_api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      schema: ${DB_SCHEMA:public}
  jpa:
    open-in-view: ${DB_OPEN_VIEW:false}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    schemas: ${DB_SCHEMA:public}
    baselineOnMigrate: ${BASE_LINE_ON_MIGRATE:true}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc:
  show-actuator: true
  version: 1.0
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_DOC_ENABLED:true}
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
    enabled: ${SWAGGER_UI_ENABLED:true}
    operationsSorter: alpha
    tagsSorter: alpha
    configUrl: ${SWAGGER_CONFIG_URL:/v3/api-docs/swagger-config}
    url: ${SWAGGER_URL:/v3/api-docs}

logging:
  level:
    org.springframework.data.repository.config.RepositoryConfigurationDelegate: WARN
    com.zaxxer.hikari: WARN
    org.hibernate.jpa.internal.util.LogHelper: WARN
    org.hibernate.Version: WARN
    org.hibernate.cache.internal.RegionFactoryInitiator: WARN
    org.springframework.orm.jpa.persistenceunit.SpringPersistenceUnitInfo: WARN
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: WARN
    org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean: WARN
    org.flywaydb.core.internal.license.VersionPrinter: WARN
    org.flywaydb.core.internal.database.base.BaseDatabaseType: WARN
    org.springframework.data.jpa.repository.query.QueryEnhancerFactory: WARN
